# Change these first
owner: alanmacdonald1
repo: uptime


sites:
  - name: HAB Reports
    url: https://www.habreports.org/
  - name: Thredds
    url: https://thredds.sams.ac.uk/
  - name: IFCB Dashboard
    url: https://ifcb-data.sams.ac.uk/
  - name: SkateSpotter
    url: https://skatespotter.sams.ac.uk/
  - name: HAB Reports (Django)
    url: https://www.habreports.org/habappusers/info/
  - name: SIMBA
    url: https://simba.srsl.com/
  - name: IFCB Portal
    url: https://ifcb-portal.sams.ac.uk/
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # cname: demo.upptime.js.org   
  publish: true
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: My Uptime
  introTitle: "**Uptime**"
  introMessage: Live status of endpoints.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
